"""Initial migration for orders table

Revision ID: 508a7c8d0f3e
Revises: 
Create Date: 2025-02-24 16:27:44.455047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508a7c8d0f3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('ingested_timestamp', sa.DateTime(), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
