name: CI / CD

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install simplefix pytest flask requests flask-cors pika Flask-SQLAlchemy Flask-Migrate psycopg2-binary

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/my_test_db
        run: |
          pytest --maxfail=1 --disable-warnings -v

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure a full clone

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Verify Heroku CLI Installation
        run: heroku --version

      - name: Deploy to Heroku using Buildpacks
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/my-new-fix-project-app.git HEAD:main
          
      - name: Scale Worker Dyno
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku ps:scale worker=1 --app my-new-fix-project-app